/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as DashboardVariantsIndexImport } from './routes/dashboard/variants/index'
import { Route as DashboardUsersIndexImport } from './routes/dashboard/users/index'
import { Route as DashboardSuppliersIndexImport } from './routes/dashboard/suppliers/index'
import { Route as DashboardShippingIndexImport } from './routes/dashboard/shipping/index'
import { Route as DashboardSettingsIndexImport } from './routes/dashboard/settings/index'
import { Route as DashboardReviewsIndexImport } from './routes/dashboard/reviews/index'
import { Route as DashboardProductsIndexImport } from './routes/dashboard/products/index'
import { Route as DashboardPaymentsIndexImport } from './routes/dashboard/payments/index'
import { Route as DashboardOrdersIndexImport } from './routes/dashboard/orders/index'
import { Route as DashboardNotificationsIndexImport } from './routes/dashboard/notifications/index'
import { Route as DashboardInventoryIndexImport } from './routes/dashboard/inventory/index'
import { Route as DashboardDiscountsIndexImport } from './routes/dashboard/discounts/index'
import { Route as DashboardCategoriesIndexImport } from './routes/dashboard/categories/index'
import { Route as DashboardSuppliersAddImport } from './routes/dashboard/suppliers/add'
import { Route as DashboardShippingAddImport } from './routes/dashboard/shipping/add'
import { Route as DashboardProductsAddImport } from './routes/dashboard/products/add'
import { Route as DashboardPaymentsAddImport } from './routes/dashboard/payments/add'
import { Route as DashboardCategoriesAddImport } from './routes/dashboard/categories/add'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const DashboardVariantsIndexRoute = DashboardVariantsIndexImport.update({
  path: '/variants/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersIndexRoute = DashboardUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSuppliersIndexRoute = DashboardSuppliersIndexImport.update({
  path: '/suppliers/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardShippingIndexRoute = DashboardShippingIndexImport.update({
  path: '/shipping/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSettingsIndexRoute = DashboardSettingsIndexImport.update({
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardReviewsIndexRoute = DashboardReviewsIndexImport.update({
  path: '/reviews/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProductsIndexRoute = DashboardProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPaymentsIndexRoute = DashboardPaymentsIndexImport.update({
  path: '/payments/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOrdersIndexRoute = DashboardOrdersIndexImport.update({
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexImport.update({
    path: '/notifications/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardInventoryIndexRoute = DashboardInventoryIndexImport.update({
  path: '/inventory/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDiscountsIndexRoute = DashboardDiscountsIndexImport.update({
  path: '/discounts/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardCategoriesIndexRoute = DashboardCategoriesIndexImport.update({
  path: '/categories/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSuppliersAddRoute = DashboardSuppliersAddImport.update({
  path: '/suppliers/add',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardShippingAddRoute = DashboardShippingAddImport.update({
  path: '/shipping/add',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProductsAddRoute = DashboardProductsAddImport.update({
  path: '/products/add',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPaymentsAddRoute = DashboardPaymentsAddImport.update({
  path: '/payments/add',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardCategoriesAddRoute = DashboardCategoriesAddImport.update({
  path: '/categories/add',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/dashboard/categories/add': {
      id: '/dashboard/categories/add'
      path: '/categories/add'
      fullPath: '/dashboard/categories/add'
      preLoaderRoute: typeof DashboardCategoriesAddImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/payments/add': {
      id: '/dashboard/payments/add'
      path: '/payments/add'
      fullPath: '/dashboard/payments/add'
      preLoaderRoute: typeof DashboardPaymentsAddImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/products/add': {
      id: '/dashboard/products/add'
      path: '/products/add'
      fullPath: '/dashboard/products/add'
      preLoaderRoute: typeof DashboardProductsAddImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/shipping/add': {
      id: '/dashboard/shipping/add'
      path: '/shipping/add'
      fullPath: '/dashboard/shipping/add'
      preLoaderRoute: typeof DashboardShippingAddImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/suppliers/add': {
      id: '/dashboard/suppliers/add'
      path: '/suppliers/add'
      fullPath: '/dashboard/suppliers/add'
      preLoaderRoute: typeof DashboardSuppliersAddImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/discounts/': {
      id: '/dashboard/discounts/'
      path: '/discounts'
      fullPath: '/dashboard/discounts'
      preLoaderRoute: typeof DashboardDiscountsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/payments/': {
      id: '/dashboard/payments/'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/reviews/': {
      id: '/dashboard/reviews/'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/shipping/': {
      id: '/dashboard/shipping/'
      path: '/shipping'
      fullPath: '/dashboard/shipping'
      preLoaderRoute: typeof DashboardShippingIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/suppliers/': {
      id: '/dashboard/suppliers/'
      path: '/suppliers'
      fullPath: '/dashboard/suppliers'
      preLoaderRoute: typeof DashboardSuppliersIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/variants/': {
      id: '/dashboard/variants/'
      path: '/variants'
      fullPath: '/dashboard/variants'
      preLoaderRoute: typeof DashboardVariantsIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardCategoriesAddRoute: typeof DashboardCategoriesAddRoute
  DashboardPaymentsAddRoute: typeof DashboardPaymentsAddRoute
  DashboardProductsAddRoute: typeof DashboardProductsAddRoute
  DashboardShippingAddRoute: typeof DashboardShippingAddRoute
  DashboardSuppliersAddRoute: typeof DashboardSuppliersAddRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardDiscountsIndexRoute: typeof DashboardDiscountsIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardPaymentsIndexRoute: typeof DashboardPaymentsIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardReviewsIndexRoute: typeof DashboardReviewsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardShippingIndexRoute: typeof DashboardShippingIndexRoute
  DashboardSuppliersIndexRoute: typeof DashboardSuppliersIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardVariantsIndexRoute: typeof DashboardVariantsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCategoriesAddRoute: DashboardCategoriesAddRoute,
  DashboardPaymentsAddRoute: DashboardPaymentsAddRoute,
  DashboardProductsAddRoute: DashboardProductsAddRoute,
  DashboardShippingAddRoute: DashboardShippingAddRoute,
  DashboardSuppliersAddRoute: DashboardSuppliersAddRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardDiscountsIndexRoute: DashboardDiscountsIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardPaymentsIndexRoute: DashboardPaymentsIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardReviewsIndexRoute: DashboardReviewsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardShippingIndexRoute: DashboardShippingIndexRoute,
  DashboardSuppliersIndexRoute: DashboardSuppliersIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardVariantsIndexRoute: DashboardVariantsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/categories/add': typeof DashboardCategoriesAddRoute
  '/dashboard/payments/add': typeof DashboardPaymentsAddRoute
  '/dashboard/products/add': typeof DashboardProductsAddRoute
  '/dashboard/shipping/add': typeof DashboardShippingAddRoute
  '/dashboard/suppliers/add': typeof DashboardSuppliersAddRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/discounts': typeof DashboardDiscountsIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/payments': typeof DashboardPaymentsIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/reviews': typeof DashboardReviewsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/shipping': typeof DashboardShippingIndexRoute
  '/dashboard/suppliers': typeof DashboardSuppliersIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/variants': typeof DashboardVariantsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/categories/add': typeof DashboardCategoriesAddRoute
  '/dashboard/payments/add': typeof DashboardPaymentsAddRoute
  '/dashboard/products/add': typeof DashboardProductsAddRoute
  '/dashboard/shipping/add': typeof DashboardShippingAddRoute
  '/dashboard/suppliers/add': typeof DashboardSuppliersAddRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/discounts': typeof DashboardDiscountsIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/payments': typeof DashboardPaymentsIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/reviews': typeof DashboardReviewsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/shipping': typeof DashboardShippingIndexRoute
  '/dashboard/suppliers': typeof DashboardSuppliersIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/variants': typeof DashboardVariantsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/categories/add': typeof DashboardCategoriesAddRoute
  '/dashboard/payments/add': typeof DashboardPaymentsAddRoute
  '/dashboard/products/add': typeof DashboardProductsAddRoute
  '/dashboard/shipping/add': typeof DashboardShippingAddRoute
  '/dashboard/suppliers/add': typeof DashboardSuppliersAddRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/discounts/': typeof DashboardDiscountsIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/payments/': typeof DashboardPaymentsIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/reviews/': typeof DashboardReviewsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/shipping/': typeof DashboardShippingIndexRoute
  '/dashboard/suppliers/': typeof DashboardSuppliersIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/variants/': typeof DashboardVariantsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/categories/add'
    | '/dashboard/payments/add'
    | '/dashboard/products/add'
    | '/dashboard/shipping/add'
    | '/dashboard/suppliers/add'
    | '/dashboard/categories'
    | '/dashboard/discounts'
    | '/dashboard/inventory'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/products'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/shipping'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/dashboard/variants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/categories/add'
    | '/dashboard/payments/add'
    | '/dashboard/products/add'
    | '/dashboard/shipping/add'
    | '/dashboard/suppliers/add'
    | '/dashboard/categories'
    | '/dashboard/discounts'
    | '/dashboard/inventory'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/products'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/shipping'
    | '/dashboard/suppliers'
    | '/dashboard/users'
    | '/dashboard/variants'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/categories/add'
    | '/dashboard/payments/add'
    | '/dashboard/products/add'
    | '/dashboard/shipping/add'
    | '/dashboard/suppliers/add'
    | '/dashboard/categories/'
    | '/dashboard/discounts/'
    | '/dashboard/inventory/'
    | '/dashboard/notifications/'
    | '/dashboard/orders/'
    | '/dashboard/payments/'
    | '/dashboard/products/'
    | '/dashboard/reviews/'
    | '/dashboard/settings/'
    | '/dashboard/shipping/'
    | '/dashboard/suppliers/'
    | '/dashboard/users/'
    | '/dashboard/variants/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/login"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/categories/add",
        "/dashboard/payments/add",
        "/dashboard/products/add",
        "/dashboard/shipping/add",
        "/dashboard/suppliers/add",
        "/dashboard/categories/",
        "/dashboard/discounts/",
        "/dashboard/inventory/",
        "/dashboard/notifications/",
        "/dashboard/orders/",
        "/dashboard/payments/",
        "/dashboard/products/",
        "/dashboard/reviews/",
        "/dashboard/settings/",
        "/dashboard/shipping/",
        "/dashboard/suppliers/",
        "/dashboard/users/",
        "/dashboard/variants/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/dashboard/categories/add": {
      "filePath": "dashboard/categories/add.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/payments/add": {
      "filePath": "dashboard/payments/add.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/products/add": {
      "filePath": "dashboard/products/add.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/shipping/add": {
      "filePath": "dashboard/shipping/add.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/suppliers/add": {
      "filePath": "dashboard/suppliers/add.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/categories/": {
      "filePath": "dashboard/categories/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/discounts/": {
      "filePath": "dashboard/discounts/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/inventory/": {
      "filePath": "dashboard/inventory/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/notifications/": {
      "filePath": "dashboard/notifications/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/orders/": {
      "filePath": "dashboard/orders/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/payments/": {
      "filePath": "dashboard/payments/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/products/": {
      "filePath": "dashboard/products/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/reviews/": {
      "filePath": "dashboard/reviews/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings/": {
      "filePath": "dashboard/settings/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/shipping/": {
      "filePath": "dashboard/shipping/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/suppliers/": {
      "filePath": "dashboard/suppliers/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/users/": {
      "filePath": "dashboard/users/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/variants/": {
      "filePath": "dashboard/variants/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
